/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/dev-guide': RouteRecordInfo<'/dev-guide', '/dev-guide', Record<never, never>, Record<never, never>>,
    '/en/': RouteRecordInfo<'/en/', '/en', Record<never, never>, Record<never, never>>,
    '/en/[...all]': RouteRecordInfo<'/en/[...all]', '/en/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/en/instances/': RouteRecordInfo<'/en/instances/', '/en/instances', Record<never, never>, Record<never, never>>,
    '/en/instances/[id]': RouteRecordInfo<'/en/instances/[id]', '/en/instances/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/en/settings': RouteRecordInfo<'/en/settings', '/en/settings', Record<never, never>, Record<never, never>>,
    '/instances/': RouteRecordInfo<'/instances/', '/instances', Record<never, never>, Record<never, never>>,
    '/instances/[id]': RouteRecordInfo<'/instances/[id]', '/instances/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/legal/rules': RouteRecordInfo<'/legal/rules', '/legal/rules', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
